import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AuthProvider } from "./AuthContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <AuthProvider>
          <GoogleOAuthProvider clientId="">{children}</GoogleOAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
